### ISSUE TITLE
Unable to find the knee/elbow?

### ISSUE THREAD

**Issue by Gabriel-p** [georg-un/kneebow#1]
Hi, first of all thank you for making this package available. I'm trying to find the knee/elbow in some data and this is what I get:

![DeepinScreenshot_Seleccionar área_20200626152006](https://user-images.githubusercontent.com/6054951/85888731-8c14d200-b7c0-11ea-8141-f1a0c42c2b6e.png)

That's a zoom of the output of `rotor.plot_elbow()`. Here's the full image:

![DeepinScreenshot_Seleccionar área_20200626152058](https://user-images.githubusercontent.com/6054951/85888812-af3f8180-b7c0-11ea-914a-1360baad1686.png)

Am I doing something wrong here?

**Comment by georg-un** [comment]
Hi @Gabriel-p , I am so sorry for this late response. Apparently, I did not have notifications turned on. 

My first guess is that this was caused by the scaling of the axes which is automatically turned on by default. You can deactivate it with the `scale` argument: `fit_rotate(scale=False)`.

Please note that without any scaling, the rotation method tends to choose points in favor of the larger axis.

**Comment by Gabriel-p** [comment]
Thank you Georg!
