### ISSUE TITLE
Potential Problem

### ISSUE THREAD

**Issue by bryannemcd** [georg-un/kneebow#2]
I ran into an issue trying to use this package as-is. Depending on whether I used the codes for elbow or knee, I got either the first or last index in my data.
get_elbow_index and get_knee_index call for either the min or max of the whole data array. This means that if you x values are larger/smaller than your y values, it can pull those as the max/min locations instead of the max/min of the y data. I was able to use the functions from the Stack Exchange post and modify them so that it pulled the min/max just from the second column of the data.

**Comment by georg-un** [comment]
Thanks for opening this issue!

By default, `fit_rotate()` normalizes every column individually in order to remove any effects from potential differences of absolute values between axes. Therefore, if you only normalize the y values, you just skew the data differently. But you can totally do that with `fit_rotate(data, scale=False)` if it makes sense for your use case.

After normalizing, `fit_rotate()` rotates the vector in such a way that the slope between the first and the last value is 0. I can only think of two scenarios that would cause `get_elbow_index()` and `get_knee_index()` to return the first or last value of the vector: either the vector is a straight line or you forgot to run `fit_rotate()` before querying the respective index.

**Comment by georg-un** [comment]
This was a misunderstanding on my side. The issue described here is the one that was fixed by #3. Sorry for the misunderstanding. The fix is included in the new version `1.0.1`.
